name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          npm install

      - name: Run All
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run all

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Action
        uses: ./
        id: hello
        with:
          who-to-greet: World
          milliseconds: 1000

      - name: Get and Test outputs
        run: |
          cd .github/workflows
          if [ ! -f assert.sh ]; then echo "Can not find assert.sh"; exit 1; fi
          chmod +x assert.sh
          ./assert.sh "${{ steps.hello.outputs.hello-message }}" "Hello World!" "hello-message"
