name: 'build-test'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - dev
    paths-ignore:
      - '**/*.md'
      - '**/*.{yml,yaml}'
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - '**/*.md'
      - '**/*.{yml,yaml}'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run All
        run: |
          cd release
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run all
